# Generated by Django 4.1.2 on 2022-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID користувача')),
                ('name', models.TextField(verbose_name="Ім'я користувача")),
                ('gender', models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], default='M', max_length=1, verbose_name='Стать користувача')),
            ],
        ),
    ]
