# Generated by Django 4.1.2 on 2022-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dish', models.CharField(max_length=50, verbose_name='name dish')),
                ('slug', models.SlugField(unique=True)),
                ('recipe', models.TextField(default='no', verbose_name='recipe')),
            ],
        ),
    ]
