# Generated by Django 4.1.2 on 2022-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_profile_options_remove_profile_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('RG', 'Реєстрація'), ('MM', 'Головне меню'), ('RM', 'Меню рецептів')], default='RG', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name_dish',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
