# Generated by Django 4.1.2 on 2022-10-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(),
        ),
    ]
